.PHONY: build release release-universal run clean test integration-test snapshot bundle bundle-universal install setup install-app open reset reset-full cert allow check-cert icons check-icons-deps check-dev-deps \
        signing-check notary-restore unlock-signing bundle-dist dmg notarize staple verify-notarization release-dmg \
        vendor-uv generate-bundle-config check-versions supply-chain-check release-dmg-smoke brand-sync \
        release-preflight bump-release

# Default goal when running bare `make` — build the project. brand-sync is
# opt-in (run it manually when the brand spec updates).
.DEFAULT_GOAL := build

# Code signing identity — run 'make cert' then 'make allow' to create and trust (one-time setup)
SIGN_IDENTITY ?= solstone dev

# Canonical brand source — only used by `make brand-sync`. Override to point
# at the sol brand source directory: BRAND_DIR=/path/to/brand make brand-sync
BRAND_DIR ?= ../sol-brand

# ---------------------------------------------------------------------------
# Distribution signing (Apple Developer ID + notarization)
#
# Activated 2026-04-20 when the sol pbc Apple Developer Program went live
# (team 7QCG8V4M6H). Certs live in a dedicated sol-signing keychain on the
# release host, isolated from the login keychain. Notarytool uses an ASC
# API key (no app-specific password).
# ---------------------------------------------------------------------------
DEVELOPER_ID_APP       ?= Developer ID Application: sol pbc (7QCG8V4M6H)
DEVELOPER_ID_INSTALLER ?= Developer ID Installer: sol pbc (7QCG8V4M6H)
NOTARY_PROFILE         ?= sol-pbc-notary
SIGNING_KEYCHAIN       ?= $(HOME)/Library/Keychains/sol-signing.keychain-db
SIGNING_KC_PASS_FILE   ?= $(HOME)/.config/sol-pbc/signing/keychain-password
# ASC API key + identifiers used by `make notary-restore` to rebuild the
# notarytool keychain profile when it evicts (the profile lives inside
# sol-signing.keychain-db and is reconstructable from these three inputs).
# Mirrors cso/vault/credentials/apple-asc-api-key.{p8,json} in the extro repo.
ASC_API_KEY_FILE       ?= $(HOME)/.config/sol-pbc/signing/apple-asc-api-key.p8
ASC_API_KEY_ID         ?= SNP7CMKMZ5
ASC_API_ISSUER         ?= 0fe42f6d-2c46-4f09-a9c2-152b20b3ea19
DIST_VERSION           := $(shell python3 -c "import plistlib; print(plistlib.load(open('Sources/solstone/Info.plist','rb'))['CFBundleShortVersionString'])" 2>/dev/null || echo 0.0.0)
DIST_BUILD             := $(shell python3 -c "import plistlib; print(plistlib.load(open('Sources/solstone/Info.plist','rb'))['CFBundleVersion'])" 2>/dev/null || echo 0)
DMG_NAME               ?= solstone-$(DIST_VERSION).dmg
SPARKLE_ARTIFACT_DIR   ?= .build/artifacts/sparkle/Sparkle
SPARKLE_FRAMEWORK      ?= $(SPARKLE_ARTIFACT_DIR)/Sparkle.xcframework/macos-arm64_x86_64/Sparkle.framework

# uv vendoring
UV_VERSION ?= 0.11.13
UV_TARBALL_NAME := uv-aarch64-apple-darwin.tar.gz
UV_RELEASE_URL_BASE ?= https://releases.astral.sh/github/uv/releases/download/$(UV_VERSION)
UV_RELEASE_URL := $(UV_RELEASE_URL_BASE)/$(UV_TARBALL_NAME)
UV_VENDOR_DIR := vendor
UV_SHA256_FILE := $(UV_VENDOR_DIR)/uv-aarch64-apple-darwin.sha256
UV_VENDOR_BINARY := $(UV_VENDOR_DIR)/uv

# version pins for installer (consumed by BundleConfig)
SOLSTONE_PIN_VERSION ?= 0.3.2
SOLSTONE_MIN_VERSION ?= 0.3.2

check-versions:
	@[ -n "$(SOLSTONE_PIN_VERSION)" ] || { echo "error: solstone pin version must not be empty"; exit 1; }
	@printf '0.2.1\n%s\n' "$(SOLSTONE_MIN_VERSION)" | sort -V -C || { echo "error: solstone minimum version must be >= 0.2.1 (got $(SOLSTONE_MIN_VERSION))"; exit 1; }

vendor-uv:
	@mkdir -p "$(UV_VENDOR_DIR)"
	@if [ -f "$(UV_VENDOR_BINARY)" ] && [ -f "$(UV_VENDOR_DIR)/$(UV_TARBALL_NAME)" ] && \
	    (cd "$(UV_VENDOR_DIR)" && shasum -a 256 -c "$(notdir $(UV_SHA256_FILE))" >/dev/null 2>&1); then \
	    echo "vendor: uv $(UV_VERSION) already present and sha matches"; \
	else \
	    echo "vendor: fetching uv $(UV_VERSION) from $(UV_RELEASE_URL)"; \
	    rm -rf "$(UV_VENDOR_DIR)/uv-aarch64-apple-darwin" "$(UV_VENDOR_BINARY)" "$(UV_VENDOR_DIR)/$(UV_TARBALL_NAME)"; \
	    curl --fail --location --retry 3 --retry-delay 2 --output "$(UV_VENDOR_DIR)/$(UV_TARBALL_NAME)" "$(UV_RELEASE_URL)"; \
	    (cd "$(UV_VENDOR_DIR)" && shasum -a 256 -c "$(notdir $(UV_SHA256_FILE))") || { echo "error: uv tarball sha256 mismatch"; exit 1; }; \
	    tar -xzf "$(UV_VENDOR_DIR)/$(UV_TARBALL_NAME)" -C "$(UV_VENDOR_DIR)"; \
	    mv "$(UV_VENDOR_DIR)/uv-aarch64-apple-darwin/uv" "$(UV_VENDOR_BINARY)"; \
	    chmod +x "$(UV_VENDOR_BINARY)"; \
	    echo "vendor: uv $(UV_VERSION) extracted to $(UV_VENDOR_BINARY)"; \
	fi

generate-bundle-config: check-versions
	@SHA="$$(awk '{print $$1; exit}' "$(UV_SHA256_FILE)")"; \
	    [ -n "$$SHA" ] || { echo "error: could not read sha from $(UV_SHA256_FILE)"; exit 1; }; \
	    { \
	        printf '%s\n' '/// machine-generated by `make generate-bundle-config`; do not edit.'; \
	        printf '%s\n' 'public enum BundleConfig {'; \
	        printf '    public static let solstonePinVersion = "%s"\n' "$(SOLSTONE_PIN_VERSION)"; \
	        printf '    public static let solstoneMinVersion = "%s"\n' "$(SOLSTONE_MIN_VERSION)"; \
	        printf '    public static let bundledUVVersion = "%s"\n' "$(UV_VERSION)"; \
	        printf '%s\n' '}'; \
	    } > Sources/solstone/BundleConfig.swift
	@echo "generated: Sources/solstone/BundleConfig.swift"

# Re-vendor brand SVGs from the canonical source. CI verifies the committed
# output (it does not run brand-sync) — run this locally when the brand spec
# updates, then commit the diff.
brand-sync:
	@test -d "$(BRAND_DIR)" || { echo "brand: $(BRAND_DIR) not found — set BRAND_DIR to the sol brand source directory (BRAND_DIR=/path/to/brand make brand-sync)"; exit 1; }
	cp "$(BRAND_DIR)/sol-wordmark.svg"          assets/sol-wordmark.svg
	cp "$(BRAND_DIR)/sol-wordmark-white.svg"    assets/sol-wordmark-white.svg
	cp "$(BRAND_DIR)/sol-ring.svg"              assets/sol-ring.svg
	cp "$(BRAND_DIR)/sol-ring-icon.svg"         assets/sol-ring-icon.svg
	cp "$(BRAND_DIR)/sol-ring-icon-error.svg"   assets/sol-ring-icon-error.svg
	cp "$(BRAND_DIR)/sol-ring-icon-paused.svg"  assets/sol-ring-icon-paused.svg
	cp "$(BRAND_DIR)/sol-ring-icon-half.svg"    assets/sol-ring-icon-half.svg
	cp "$(BRAND_DIR)/sol-app-icon.svg"          assets/icon-app.svg
	cp "$(BRAND_DIR)/sol-app-icon-16.svg"       assets/icon-app-16.svg
	cp "$(BRAND_DIR)/sol-app-icon-32.svg"       assets/icon-app-32.svg
	@echo "brand: synced from $(BRAND_DIR)"

# Build debug version
build:
	swift build

# Build release version
release:
	swift build -c release

# Build universal binary (arm64 + x86_64)
release-universal:
	swift build -c release --arch arm64 --arch x86_64
	swift build -c release --arch arm64 --arch x86_64 --product sol-mac

# Run the installed app and stream all logs to a timestamped file in scratch/
# Keeps capturing across app restarts. Ctrl+C to stop.
run:
	@mkdir -p scratch; \
	LOG=scratch/$$(date +%Y%m%d_%H%M%S).log; \
	echo "Streaming logs → $$LOG  (Ctrl+C to stop)"; \
	/usr/bin/log stream --predicate 'subsystem == "app.solstone.observer"' --level debug > "$$LOG" 2>&1 & \
	STREAM_PID=$$!; \
	open /Applications/solstone.app; \
	trap "kill $$STREAM_PID 2>/dev/null; echo; echo 'Log saved: $$LOG'" INT TERM; \
	wait $$STREAM_PID

# Clean all build artifacts
clean:
	swift package clean
	rm -rf .build
	rm -rf solstone.app

# Run tests
test:
	swift test

integration-test:
	SPL_INTEGRATION=1 swift test --filter 'SPLTunnelTests.IntegrationTests'

# Render view snapshots
snapshot:
	swift test --filter Snapshot

check-dev-deps:
	@xcodebuild -version > /dev/null 2>&1 || \
		{ echo "error: Xcode is required for local builds"; \
		  echo "       install the full Xcode app from the Mac App Store, then run it once"; \
		  exit 1; }

check-cert:
	@if security find-identity -v -p codesigning 2>/dev/null | grep -q '"$(SIGN_IDENTITY)"'; then \
		exit 0; \
	elif security find-identity -p codesigning 2>/dev/null | grep -q '"$(SIGN_IDENTITY)"'; then \
		echo "error: certificate '$(SIGN_IDENTITY)' exists but is not trusted"; \
		echo "       run 'make allow' — macOS will ask for your password"; \
		exit 1; \
	else \
		echo "error: signing identity '$(SIGN_IDENTITY)' not found in keychain"; \
		echo "       run 'make cert' then 'make allow' to create one"; \
		exit 1; \
	fi

# Create app bundle for distribution
bundle: check-cert release
	@echo "Creating app bundle..."
	@rm -rf solstone.app
	@mkdir -p solstone.app/Contents/MacOS
	@mkdir -p solstone.app/Contents/Resources
	@cp .build/release/solstone solstone.app/Contents/MacOS/
	@cp .build/release/sol-mac solstone.app/Contents/MacOS/
	@cp Sources/solstone/Info.plist solstone.app/Contents/
	@cp Sources/solstone/Resources/AppIcon.icns solstone.app/Contents/Resources/
	@cp -r .build/release/solstone_solstone.bundle solstone.app/Contents/Resources/
	@codesign --force --deep --sign "$(SIGN_IDENTITY)" --entitlements Sources/solstone/entitlements.plist solstone.app
	@echo "Created solstone.app"

# Create universal app bundle
bundle-universal: release-universal
	@echo "Creating universal app bundle..."
	@rm -rf solstone.app
	@mkdir -p solstone.app/Contents/MacOS
	@mkdir -p solstone.app/Contents/Resources
	@cp .build/apple/Products/Release/solstone solstone.app/Contents/MacOS/
	@cp .build/apple/Products/Release/sol-mac solstone.app/Contents/MacOS/
	@cp Sources/solstone/Info.plist solstone.app/Contents/
	@cp Sources/solstone/Resources/AppIcon.icns solstone.app/Contents/Resources/
	@cp -r .build/apple/Products/Release/solstone_solstone.bundle solstone.app/Contents/Resources/
	@codesign --force --deep --sign "$(SIGN_IDENTITY)" --entitlements Sources/solstone/entitlements.plist solstone.app
	@echo "Created universal solstone.app"

# =======================================================================
# Distribution pipeline: Developer ID signed + notarized DMG
#
# Use `make release-dmg` to produce a signed, notarized, stapled DMG ready
# to hand out for ad-hoc install. All signing runs headless over SSH using
# the sol-signing keychain (see header). For local debug builds continue
# to use `bundle` / `bundle-universal` (self-signed `solstone dev` cert).
# =======================================================================

# Read-only check that Developer ID certs + notary profile are ready.
# If the notary profile has evicted (recurring failure mode), auto-heal
# from the local ASC API key. Cert checks remain hard-fail because cert
# loss is a different class of problem and warrants founder attention.
signing-check:
	@security find-identity -v -p codesigning | grep -q '"$(DEVELOPER_ID_APP)"' || \
		{ echo "error: '$(DEVELOPER_ID_APP)' not found in any keychain on the search list"; \
		  echo "       ensure $(SIGNING_KEYCHAIN) is in 'security list-keychains -d user'"; \
		  exit 1; }
	@security find-identity -v | grep -q '"$(DEVELOPER_ID_INSTALLER)"' || \
		{ echo "error: '$(DEVELOPER_ID_INSTALLER)' not found"; exit 1; }
	@xcrun notarytool history --keychain-profile "$(NOTARY_PROFILE)" --keychain "$(SIGNING_KEYCHAIN)" > /dev/null 2>&1 || \
		{ echo "notarytool profile '$(NOTARY_PROFILE)' missing — auto-restoring from $(ASC_API_KEY_FILE)…"; \
		  $(MAKE) -s notary-restore; }
	@echo "✓ Developer ID certs + notary profile ready"

# Rebuild the notarytool keychain profile from the local ASC API key.
# Idempotent — safe to re-run. Use when `signing-check` fails on the
# notary profile (most common failure mode: profile evicts after OS
# updates, keychain rotation, or other tool churn). The .p8 + key-id +
# issuer-id are the source of truth; the profile is reconstructable
# from them.
notary-restore: unlock-signing
	@test -f "$(ASC_API_KEY_FILE)" || \
		{ echo "error: ASC API key missing at $(ASC_API_KEY_FILE)"; \
		  echo "       copy from extro vault: scp cso/vault/credentials/apple-asc-api-key.p8 pro5e.local:$(ASC_API_KEY_FILE) && ssh pro5e.local chmod 600 $(ASC_API_KEY_FILE)"; \
		  exit 1; }
	@xcrun notarytool store-credentials "$(NOTARY_PROFILE)" \
		--key "$(ASC_API_KEY_FILE)" \
		--key-id "$(ASC_API_KEY_ID)" \
		--issuer "$(ASC_API_ISSUER)" \
		--keychain "$(SIGNING_KEYCHAIN)" >/dev/null
	@echo "✓ notarytool profile '$(NOTARY_PROFILE)' restored in $(SIGNING_KEYCHAIN)"

# Pre-flight gate before kicking off `make release-dmg`. Catches the
# 2026-05-12 ghost-fix scenario where in-session swift edits were live on
# disk during the cold smoke but never committed — a rebuild would have
# shipped without them. Verifies: working tree clean, on a branch tracking
# origin, no stale signing/build processes that might hold a keychain
# prompt open, signing-check (which auto-heals notary profile).
release-preflight: signing-check
	@if ! git diff --quiet || ! git diff --cached --quiet; then \
		echo "error: working tree has uncommitted changes — commit or stash before release"; \
		git status --short; \
		exit 1; \
	fi
	@STALE="$$(ps aux | grep -E 'tmux-run|notarytool|sign-and|wheel-macos|codesign' | grep -v grep | grep -v 'release-preflight' || true)"; \
		[ -z "$$STALE" ] || { \
			echo "error: stale signing/build processes — one may be holding a keychain prompt:"; \
			echo "$$STALE"; \
			echo "       investigate with tmux capture-pane, then 'pkill -9 -f <pattern>'"; \
			exit 1; \
		}
	@BRANCH="$$(git rev-parse --abbrev-ref HEAD)"; \
		[ "$$BRANCH" = "main" ] || { echo "warn: releasing from non-main branch '$$BRANCH'"; }
	@AHEAD="$$(git rev-list --count @{u}..HEAD 2>/dev/null || echo 0)"; \
		[ "$$AHEAD" = "0" ] || { echo "warn: $$AHEAD local commit(s) ahead of upstream — push before release"; }
	@echo "✓ release pre-flight clean: tree clean, no stale processes, signing ready"

# Bump the .app's user-visible version + the bundled-solstone pin in one
# shot. Sole entry point for "what changes for a new release" — keeps
# Info.plist, Makefile pins, BundleConfig, and CHANGELOG.md in sync so
# no piece gets forgotten.
#
# Usage: make bump-release VERSION=1.1.4 BUILD=6 SOLSTONE=0.3.3
#   VERSION  required, semver — sets CFBundleShortVersionString
#   BUILD    required, integer — sets CFBundleVersion (must be > current)
#   SOLSTONE optional — sets SOLSTONE_PIN_VERSION + SOLSTONE_MIN_VERSION;
#            omit to keep the current pin.
#
# Side effects: Info.plist updated via plutil, Makefile pins updated via
# sed, BundleConfig.swift regenerated, CHANGELOG.md scaffold prepended
# for the new version (date defaults to today). Does NOT commit — review
# the diff, fill in the CHANGELOG body, then commit + push.
bump-release:
	@test -n "$(VERSION)" || { echo "error: VERSION=... required (e.g. VERSION=1.1.4)"; exit 1; }
	@test -n "$(BUILD)"   || { echo "error: BUILD=... required (e.g. BUILD=6)"; exit 1; }
	@CURRENT_BUILD="$(DIST_BUILD)"; \
		python3 -c "import sys; sys.exit(0 if int('$(BUILD)') > int('$$CURRENT_BUILD') else 1)" || \
		{ echo "error: BUILD=$(BUILD) must be strictly greater than current $$CURRENT_BUILD (Sparkle uses CFBundleVersion for 'is newer?')"; exit 1; }
	@/usr/bin/plutil -replace CFBundleShortVersionString -string "$(VERSION)" Sources/solstone/Info.plist
	@/usr/bin/plutil -replace CFBundleVersion -string "$(BUILD)" Sources/solstone/Info.plist
	@echo "✓ Info.plist: CFBundleShortVersionString=$(VERSION), CFBundleVersion=$(BUILD)"
	@if [ -n "$(SOLSTONE)" ]; then \
		sed -i '' "s/^SOLSTONE_PIN_VERSION ?= .*/SOLSTONE_PIN_VERSION ?= $(SOLSTONE)/" Makefile; \
		sed -i '' "s/^SOLSTONE_MIN_VERSION ?= .*/SOLSTONE_MIN_VERSION ?= $(SOLSTONE)/" Makefile; \
		echo "✓ Makefile pins: SOLSTONE_PIN_VERSION = $(SOLSTONE)"; \
		$(MAKE) -s SOLSTONE_PIN_VERSION="$(SOLSTONE)" SOLSTONE_MIN_VERSION="$(SOLSTONE)" generate-bundle-config; \
	else \
		$(MAKE) -s generate-bundle-config; \
	fi
	@if grep -q "^## \[$(VERSION)\]" CHANGELOG.md; then \
		echo "note: CHANGELOG.md already has an entry for $(VERSION); leaving it alone"; \
	else \
		TODAY="$$(date +%Y-%m-%d)"; \
		awk -v v="$(VERSION)" -v d="$$TODAY" 'NR==1 {print; next} /^## \[/ && !inserted {print "## [" v "] - " d "\n\n### Added\n- (describe new user-visible additions)\n\n### Changed\n- (describe behavior changes)\n\n### Fixed\n- (describe bug fixes)\n\n"; inserted=1} {print}' CHANGELOG.md > CHANGELOG.md.tmp && mv CHANGELOG.md.tmp CHANGELOG.md; \
		echo "✓ CHANGELOG.md: scaffolded entry for [$(VERSION)] — $$TODAY (FILL IN BEFORE COMMIT)"; \
	fi
	@echo ""
	@echo "next steps:"
	@echo "  1. edit CHANGELOG.md — replace scaffold bullets with real release notes"
	@echo "  2. git diff to review"
	@echo "  3. git add Sources/solstone/Info.plist Makefile Sources/solstone/BundleConfig.swift CHANGELOG.md"
	@echo "  4. git commit -m 'release: bump to $(VERSION) (build $(BUILD))'"
	@echo "  5. git push origin main"
	@echo "  6. make release-preflight && make release-dmg"

# Unlock the sol-signing keychain and add it to the session search list.
# Fresh SSH sessions don't always inherit the user-domain search list, so
# setting it here makes `make signing-check` work from any session (not just
# the persistent hopper:build tmux window).
unlock-signing:
	@security list-keychains -s "$(SIGNING_KEYCHAIN)" "$(HOME)/Library/Keychains/login.keychain-db" >/dev/null
	@if [ -f "$(SIGNING_KC_PASS_FILE)" ]; then \
		security unlock-keychain -p "$$(cat $(SIGNING_KC_PASS_FILE))" "$(SIGNING_KEYCHAIN)"; \
	else \
		echo "warn: $(SIGNING_KC_PASS_FILE) missing — signing keychain may be locked"; \
	fi

# Build a universal .app bundle signed with Developer ID Application + hardened runtime.
# Separate from `bundle-universal` so distribution signing is additive, not destructive —
# existing self-signed bundle target stays for local dev.
bundle-dist: unlock-signing signing-check vendor-uv generate-bundle-config release-universal
	@echo "Creating distribution app bundle..."
	@rm -rf solstone.app
	@mkdir -p solstone.app/Contents/MacOS solstone.app/Contents/Resources solstone.app/Contents/Frameworks
	@cp .build/apple/Products/Release/solstone solstone.app/Contents/MacOS/
	@cp .build/apple/Products/Release/sol-mac solstone.app/Contents/MacOS/
	@cp Sources/solstone/Info.plist solstone.app/Contents/
	@cp Sources/solstone/Resources/AppIcon.icns solstone.app/Contents/Resources/
	@cp -r .build/apple/Products/Release/solstone_solstone.bundle solstone.app/Contents/Resources/
	@cp -R "$(SPARKLE_FRAMEWORK)" solstone.app/Contents/Frameworks/
	@# arm64-only uv; .app remains universal for graceful Intel detection by sol-mac installer
	@cp $(UV_VENDOR_BINARY) solstone.app/Contents/Resources/uv
	@chmod +x solstone.app/Contents/Resources/uv
	@install_name_tool -add_rpath "@executable_path/../Frameworks" solstone.app/Contents/MacOS/solstone
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Installer.xpc
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Frameworks/Sparkle.framework
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Resources/solstone_solstone.bundle
	@codesign --force --options runtime --timestamp \
		--identifier app.solstone.observer.cli \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/MacOS/sol-mac
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		solstone.app/Contents/Resources/uv
	@codesign --verify --strict --verbose=2 solstone.app/Contents/Resources/uv
	@codesign -dvvv solstone.app/Contents/Resources/uv 2>&1 | grep -q 'TeamIdentifier=7QCG8V4M6H' || { echo "error: uv missing team id 7QCG8V4M6H"; exit 1; }
	@codesign -dvvv solstone.app/Contents/Resources/uv 2>&1 | grep -q 'flags=0x10000(runtime)' || { echo "error: uv missing hardened runtime flag"; exit 1; }
	@codesign --force --options runtime --timestamp \
		--sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" \
		--entitlements Sources/solstone/entitlements.plist \
		solstone.app
	@codesign --verify --strict --deep --verbose=2 solstone.app
	@echo "✓ Signed: solstone.app"

# Create and sign the DMG using create-dmg. Produces a polished mounted
# volume — cream brand background with sol-ring watermark, app icon
# left-centered, Applications shortcut right-centered, arrow between.
# Window dimensions are logical points; background PNG ships @2x so it
# stays crisp on Retina.
#
# create-dmg builds an unsigned DMG; we codesign with --timestamp after
# (notarization needs the secure timestamp, and create-dmg doesn't pass
# extra codesign flags through).
#
# Requires: brew install create-dmg
dmg: bundle-dist
	@rm -f $(DMG_NAME)
	@create-dmg \
	  --volname "solstone" \
	  --background assets/dmg-background@2x.png \
	  --window-pos 200 200 \
	  --window-size 640 400 \
	  --icon-size 128 \
	  --icon "solstone.app" 180 200 \
	  --app-drop-link 460 200 \
	  --hide-extension "solstone.app" \
	  --no-internet-enable \
	  $(DMG_NAME) solstone.app
	@codesign --force --timestamp --sign "$(DEVELOPER_ID_APP)" --keychain "$(SIGNING_KEYCHAIN)" $(DMG_NAME)
	@echo "✓ Built: $(DMG_NAME)"

# Submit for notarization and block until Apple responds.
notarize: dmg
	@echo "Submitting $(DMG_NAME) for notarization (typically 1-5 min)…"
	@xcrun notarytool submit $(DMG_NAME) \
		--keychain-profile "$(NOTARY_PROFILE)" --keychain "$(SIGNING_KEYCHAIN)" \
		--wait

# Attach the notarization ticket to the DMG so Gatekeeper works offline.
staple: notarize
	@xcrun stapler staple $(DMG_NAME)

# Confirm the DMG will pass Gatekeeper on a fresh Mac.
verify-notarization: staple
	@spctl --assess --type open --context context:primary-signature -v $(DMG_NAME) || \
		{ echo "spctl verification failed"; exit 1; }
	@xcrun stapler validate $(DMG_NAME)
	@codesign --verify --strict --verbose=2 solstone.app/Contents/MacOS/sol-mac || \
		{ echo "inner CLI signature invalid"; exit 1; }
	@codesign -dvvv solstone.app/Contents/MacOS/sol-mac 2>&1 | grep -q 'TeamIdentifier=7QCG8V4M6H' || \
		{ echo "inner CLI missing Team ID 7QCG8V4M6H"; exit 1; }
	@codesign -dvvv solstone.app/Contents/MacOS/sol-mac 2>&1 | grep -q 'flags=0x10000(runtime)' || \
		{ echo "inner CLI missing hardened runtime flag"; exit 1; }
	@codesign -dvvv solstone.app/Contents/MacOS/sol-mac 2>&1 | grep -q 'Identifier=app.solstone.observer.cli' || \
		{ echo "inner CLI identifier mismatch (expected app.solstone.observer.cli)"; exit 1; }
	@lipo -archs solstone.app/Contents/MacOS/sol-mac | grep -q 'arm64' || \
		{ echo "inner CLI missing arm64 slice"; exit 1; }
	@lipo -archs solstone.app/Contents/MacOS/sol-mac | grep -q 'x86_64' || \
		{ echo "inner CLI missing x86_64 slice"; exit 1; }
	@codesign --verify --strict --verbose=2 solstone.app/Contents/Resources/uv
	@codesign -dvvv solstone.app/Contents/Resources/uv 2>&1 | grep -q 'TeamIdentifier=7QCG8V4M6H' || { echo "error: uv missing team id"; exit 1; }
	@codesign -dvvv solstone.app/Contents/Resources/uv 2>&1 | grep -q 'flags=0x10000(runtime)' || { echo "error: uv missing hardened runtime flag"; exit 1; }
	@lipo -archs solstone.app/Contents/Resources/uv | grep -q 'arm64' || { echo "error: uv missing arm64 slice"; exit 1; }
	@echo "✓ $(DMG_NAME) notarized + stapled (inner CLI signature verified)"

# One-shot: build + sign + notarize + staple + verify. This is the canonical
# entry point for creating an ad-hoc distributable DMG.
release-dmg: verify-notarization
	@echo ""
	@echo "✅ Distribution DMG ready: $(DMG_NAME)"
	@echo "   Signed:  $(DEVELOPER_ID_APP)"
	@echo "   Notary:  $(NOTARY_PROFILE)"
	@echo "   Size:    $$(du -h $(DMG_NAME) | cut -f1)"

supply-chain-check: vendor-uv generate-bundle-config
	@echo "── supply chain checklist ──"
	@echo "uv version: $(UV_VERSION)"
	@echo "uv release url: $(UV_RELEASE_URL)"
	@echo "uv sha256: $$(awk '{print $$1; exit}' "$(UV_SHA256_FILE)")"
	@echo "── BundleConfig.swift ──"
	@cat Sources/solstone/BundleConfig.swift
	@echo "── bundled-uv codesign ──"
	@if [ -f solstone.app/Contents/Resources/uv ]; then \
	    codesign -dvvv solstone.app/Contents/Resources/uv 2>&1 || true; \
	else \
	    echo "(not signed yet — run make bundle-dist to produce signed bundled uv)"; \
	fi
	@echo "── THIRD_PARTY_NOTICES.md ──"
	@test -f THIRD_PARTY_NOTICES.md || { echo "error: THIRD_PARTY_NOTICES.md missing"; exit 1; }
	@grep -qiE '^##[[:space:]]+uv' THIRD_PARTY_NOTICES.md || { echo "error: THIRD_PARTY_NOTICES.md missing uv entry"; exit 1; }
	@echo "supply-chain checklist: ok"

release-dmg-smoke:
	@test -f "$(DMG_NAME)" || { echo "error: $(DMG_NAME) not found — run make release-dmg first"; exit 1; }
	@MOUNT="$$(mktemp -d -t solstone-smoke)"; \
	    trap "hdiutil detach \"$$MOUNT\" -quiet -force >/dev/null 2>&1 || true; rm -rf \"$$MOUNT\"" EXIT; \
	    hdiutil attach "$(DMG_NAME)" -mountpoint "$$MOUNT" -nobrowse -quiet || { echo "error: hdiutil attach failed"; exit 1; }; \
	    codesign --verify --strict --deep --verbose=2 "$$MOUNT/solstone.app" || { echo "error: dmg .app codesign verify failed"; exit 1; }; \
	    OUT="$$("$$MOUNT/solstone.app/Contents/Resources/uv" --version 2>&1)"; \
	    echo "uv --version output: $$OUT"; \
	    echo "$$OUT" | grep -q "$(UV_VERSION)" || { echo "error: bundled uv reported wrong version (expected $(UV_VERSION))"; exit 1; }; \
	    echo "release-dmg-smoke: ok"

# Install development dependencies needed for local build workflows
install: check-dev-deps
	@if command -v brew > /dev/null 2>&1; then \
		if command -v rsvg-convert > /dev/null 2>&1; then \
			echo "librsvg already installed"; \
		else \
			echo "Installing librsvg via Homebrew..."; \
			brew install librsvg; \
		fi; \
	else \
		echo "Homebrew not found; skipping optional icon dependency (librsvg)"; \
		echo "Install Homebrew and run 'brew install librsvg' if you need 'make icons'"; \
	fi
	@echo "Development dependencies are ready."
	@echo "Use 'make build' for a debug build or 'make install-app' to bundle and copy the app to /Applications."

# Alias for install
setup: install

# Install the bundled app to /Applications
install-app: bundle
	@rm -rf /Applications/solstone.app
	@cp -r solstone.app /Applications/
	@echo "Installed to /Applications/solstone.app"

# Open the app
open: bundle
	open solstone.app

# Reset TCC permissions and app defaults for testing.
# NOTE: ScreenCapture is intentionally omitted — on macOS 26, tccutil reset ScreenCapture
# without sudo writes a DENIED entry to system TCC.db (it can't clear it without privileges),
# which silently blocks the permission dialog. Use: sudo tccutil reset All app.solstone.observer
reset:
	-tccutil reset Microphone app.solstone.observer
	-defaults delete app.solstone.observer 2>/dev/null
	-rm -f ~/Library/Preferences/app.solstone.observer.plist
	@echo "Microphone TCC and defaults reset."
	@echo "To fully reset screen recording: sudo tccutil reset All app.solstone.observer"

# Full "as-if-new-machine" wipe for reproducing first-run flows.
# Preserves captures/, parakeet/, journal/ — sync state is just a UserDefaults cache,
# segments are the source of truth and will be picked up by the next install.
# Steps requiring sudo or GUI interaction are echoed at the end, not executed
# (tccutil ScreenCapture without sudo writes a DENIED row on macOS 26 — worse than skipping).
reset-full:
	@echo "==> quitting solstone..."
	-@osascript -e 'tell application "solstone" to quit' 2>/dev/null
	-@killall -9 solstone sol-mac 2>/dev/null
	@echo "==> removing installed app + cli symlink..."
	-@rm -rf /Applications/solstone.app
	-@rm -f $(HOME)/.local/bin/sol-mac
	@echo "==> wiping app state (keeping captures/, parakeet/, journal/)..."
	-@rm -f  "$(HOME)/Library/Application Support/Solstone/sol-mac.sock"
	-@rm -f  "$(HOME)/Library/Application Support/Solstone/config.json.migrated"
	-@rm -rf "$(HOME)/Library/Application Support/Solstone/logs"
	-@rm -f  $(HOME)/Library/Preferences/app.solstone.capture.plist
	-@rm -f  $(HOME)/Library/Preferences/app.solstone.observer.plist
	-@rm -f  $(HOME)/Library/Preferences/app.solstone.observer.tests.*.plist
	-@killall cfprefsd 2>/dev/null
	@echo "==> clearing caches + LaunchServices registration..."
	-@rm -rf $(HOME)/Library/Caches/app.solstone.* $(HOME)/Library/Caches/com.solstone.* $(HOME)/Library/Caches/sol-mac
	-@rm -rf "$(HOME)/Library/Saved Application State/app.solstone."* "$(HOME)/Library/Saved Application State/com.solstone."*
	-@/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user >/dev/null 2>&1 || true
	@echo ""
	@echo "Local state wiped. Captures preserved at:"
	@echo "  $(HOME)/Library/Application Support/Solstone/captures/"
	@echo ""
	@echo "MANUAL STEPS REMAINING (need sudo / GUI interaction):"
	@echo ""
	@echo "  1. reset TCC entries (requires sudo — unsudoed tccutil writes a DENIED"
	@echo "     row on Tahoe and silently blocks the dialog):"
	@echo "       sudo tccutil reset All app.solstone.observer"
	@echo "       sudo tccutil reset All app.solstone.capture"
	@echo ""
	@echo "  2. open System Settings and remove any stale 'solstone' rows the GUI"
	@echo "     still shows (CDHash-tied entries that tccutil can leave behind):"
	@echo "       open 'x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture'"
	@echo "     check both Screen & System Audio Recording and Microphone."
	@echo ""
	@echo "  3. reboot to flush cfprefsd, tccd, and IconServices:"
	@echo "       sudo shutdown -r now"
	@echo ""
	@echo "Then: make install-app && open /Applications/solstone.app"

# Create a self-signed code signing certificate in your login keychain (one-time setup).
# Using a named cert instead of ad-hoc (-) gives a stable designated requirement so
# TCC permissions survive rebuilds. Run 'make allow' after this to trust the certificate.
cert:
	@if security find-identity -v -p codesigning 2>/dev/null | grep -q '"$(SIGN_IDENTITY)"'; then \
		echo "Certificate '$(SIGN_IDENTITY)' already exists and is trusted — nothing to do."; \
		exit 0; \
	fi
	@if security find-identity -p codesigning 2>/dev/null | grep -q '"$(SIGN_IDENTITY)"'; then \
		echo "Certificate '$(SIGN_IDENTITY)' exists but is not trusted — run 'make allow'."; \
		exit 0; \
	fi
	@echo "Creating self-signed code signing certificate '$(SIGN_IDENTITY)'..."
	@TMPDIR=$$(mktemp -d); \
	PASS=$$(openssl rand -hex 16); \
	printf '[req]\ndistinguished_name=dn\nx509_extensions=v3\nprompt=no\n[dn]\nCN=$(SIGN_IDENTITY)\n[v3]\nkeyUsage=critical,digitalSignature,keyCertSign\nextendedKeyUsage=codeSigning\nbasicConstraints=critical,CA:TRUE\n' \
		> $$TMPDIR/cert.conf; \
	openssl genrsa -out $$TMPDIR/key.pem 2048 2>/dev/null; \
	openssl req -new -x509 -key $$TMPDIR/key.pem -out $$TMPDIR/cert.pem \
		-days 3650 -config $$TMPDIR/cert.conf 2>/dev/null; \
	openssl pkcs12 -export -legacy -out $$TMPDIR/cert.p12 \
		-inkey $$TMPDIR/key.pem -in $$TMPDIR/cert.pem -passout pass:$$PASS 2>/dev/null; \
	security import $$TMPDIR/cert.p12 \
		-k "$$HOME/Library/Keychains/login.keychain-db" \
		-T /usr/bin/codesign -P "$$PASS"; \
	rm -rf $$TMPDIR; \
	echo "Certificate created. Now run 'make allow' — macOS will ask for your password."

# Trust the self-signed certificate for code signing (one-time setup).
# This MUST be run by a human at the Mac — macOS shows a system password dialog
# that cannot be bypassed or automated. Agents cannot run this step.
allow:
	@if security find-identity -v -p codesigning 2>/dev/null | grep -q '"$(SIGN_IDENTITY)"'; then \
		echo "Certificate '$(SIGN_IDENTITY)' is already trusted — nothing to do."; \
		exit 0; \
	fi
	@security find-certificate -c "$(SIGN_IDENTITY)" -p \
		"$$HOME/Library/Keychains/login.keychain-db" > /dev/null 2>&1 || \
		{ echo "error: certificate '$(SIGN_IDENTITY)' not found — run 'make cert' first"; exit 1; }
	@echo "Trusting certificate '$(SIGN_IDENTITY)' — macOS will ask for your password..."
	@CERT=$$(security find-certificate -c "$(SIGN_IDENTITY)" -p \
		"$$HOME/Library/Keychains/login.keychain-db"); \
	TMPFILE=$$(mktemp); \
	echo "$$CERT" > $$TMPFILE; \
	security add-trusted-cert -r trustRoot \
		-k "$$HOME/Library/Keychains/login.keychain-db" $$TMPFILE; \
	rm -f $$TMPFILE; \
	echo "Done — '$(SIGN_IDENTITY)' is trusted. Run 'make install-app' to build and install."

# Generate icon assets from SVG sources in assets/
# Requires: rsvg-convert (brew install librsvg), iconutil (built-in macOS)
# Run when SVGs change. Output files are committed so fresh checkouts build cleanly.
icons: check-icons-deps
	@echo "Generating icons from SVG sources..."
	@mkdir -p Sources/solstone/Resources
	@TMPDIR=$$(mktemp -d) && \
	ICONSET=$$TMPDIR/AppIcon.iconset && \
	mkdir -p $$ICONSET && \
	\
	echo "  Rendering app icon sizes (per-size SVG selection — never downsample)..." && \
	for size in 16 32 64 128 256 512 1024; do \
		svg=assets/icon-app.svg; \
		if [ -f assets/icon-app-$${size}.svg ]; then \
			svg=assets/icon-app-$${size}.svg; \
		fi; \
		rsvg-convert -w $$size -h $$size $$svg \
			-o $$TMPDIR/icon_$${size}.png; \
		echo "    $${size}x$${size}  ($$svg)"; \
	done && \
	\
	cp $$TMPDIR/icon_16.png    $$ICONSET/icon_16x16.png && \
	cp $$TMPDIR/icon_32.png    $$ICONSET/icon_16x16@2x.png && \
	cp $$TMPDIR/icon_32.png    $$ICONSET/icon_32x32.png && \
	cp $$TMPDIR/icon_64.png    $$ICONSET/icon_32x32@2x.png && \
	cp $$TMPDIR/icon_128.png   $$ICONSET/icon_128x128.png && \
	cp $$TMPDIR/icon_256.png   $$ICONSET/icon_128x128@2x.png && \
	cp $$TMPDIR/icon_256.png   $$ICONSET/icon_256x256.png && \
	cp $$TMPDIR/icon_512.png   $$ICONSET/icon_256x256@2x.png && \
	cp $$TMPDIR/icon_512.png   $$ICONSET/icon_512x512.png && \
	cp $$TMPDIR/icon_1024.png  $$ICONSET/icon_512x512@2x.png && \
	\
	iconutil -c icns $$ICONSET -o Sources/solstone/Resources/AppIcon.icns && \
	echo "  ✓ AppIcon.icns" && \
	\
	echo "  Rendering status bar template icons (vector PDF — renders crisp at any density)..." && \
		rsvg-convert -f pdf assets/sol-ring-mb.svg \
			-o Sources/solstone/Resources/sol-ring-template.pdf && \
		echo "  ✓ sol-ring-template.pdf" && \
		echo "  Rendering status bar variant icons..." && \
		rsvg-convert -f pdf assets/sol-ring-mb-error.svg \
			-o Sources/solstone/Resources/sol-ring-icon-error-template.pdf && \
		echo "  ✓ sol-ring-icon-error-template.pdf" && \
		rsvg-convert -f pdf assets/sol-ring-mb-paused.svg \
			-o Sources/solstone/Resources/sol-ring-icon-paused-template.pdf && \
		echo "  ✓ sol-ring-icon-paused-template.pdf" && \
		rsvg-convert -f pdf assets/sol-ring-mb-half.svg \
			-o Sources/solstone/Resources/sol-ring-icon-half-template.pdf && \
	echo "  ✓ sol-ring-icon-half-template.pdf" && \
	\
	echo "  Rendering wordmark for UI..." && \
	rsvg-convert -w 128 -h 128 assets/sol-wordmark.svg \
		-o Sources/solstone/Resources/sol-wordmark.png && \
	rsvg-convert -w 256 -h 256 assets/sol-wordmark.svg \
		-o Sources/solstone/Resources/sol-wordmark@2x.png && \
	echo "  ✓ sol-wordmark.png + @2x" && \
	\
	rm -rf $$TMPDIR && \
	echo "Icons generated in Sources/solstone/Resources/"

check-icons-deps:
	@which rsvg-convert > /dev/null 2>&1 || \
		(echo "error: rsvg-convert not found — run: brew install librsvg"; exit 1)
	@which iconutil > /dev/null 2>&1 || \
		(echo "error: iconutil not found (requires macOS)"; exit 1)

# ────────────────────────────────────────────────────────────────
# Publish targets — RELEASE HOST ONLY
# Do not run from a developer workstation. These are invoked from the
# release host during the release playbook. They require wrangler and the
# local vault private key.
# ────────────────────────────────────────────────────────────────
publish-appcast:
	python3 scripts/publish-appcast.py $(DIST_VERSION)

publish-appcast-staging:
	python3 scripts/publish-appcast.py $(DIST_VERSION) --staging

.PHONY: publish-appcast publish-appcast-staging
