/// machine-generated by `make generate-bundle-config`; do not edit.
public enum BundleConfig {
    public static let solstonePinVersion = "0.8.2"
    public static let solstoneMinVersion = "0.8.2"
    public static let bundledUVVersion = "0.11.13"
    public static let bundledPythonBuild = "20260510"
}
