import Foundation

enum InstallerCopy {
    static let windowTitle = "set up solstone"
    static let pitch = "solstone is two halves: the journal and observer. this app is the observer. install the other half locally, or point it at an existing service."
    static let installButton = "install solstone for me"
    static let existingButton = "i already have solstone elsewhere"
    static let learnMore = "learn more →"
    static let learnMoreURL = "https://solstone.app/install"
    static let state1Label = "checking your system"
    static let state2Label = "installing solstone"
    static let state3Label = "setting up your journal"
    static let state3aLabel = "downloading the transcription model (this can take a few minutes)"
    static let state4Label = "registering this observer"
    static let stepOk = "done"
    static let stepFailedPrefix = "couldn't finish — "
    static let retryButton = "try again"
    static let showLogLabel = "show details"
    static let hideLogLabel = "hide details"
    static let journalLocationLabel = "journal location"
    static let journalChangeLink = "change..."
    static let journalPickerTitle = "choose journal location"
    static let journalTccWarning = "macos may ask permission to write here."
    static let doneTitle = "you're all set"
    static let doneBody = "solstone is running on this mac. we opened the setup page in your browser — finish there to choose a password and connect your gemini key."
    static let donePermissions = "next you'll be asked for screen recording, microphone, and system audio access."
}
