public enum UICopy {
    public static let JOURNAL_MODE_THIS_MAC_LABEL = "this Mac"
    public static let JOURNAL_MODE_ANOTHER_MACHINE_LABEL = "another device"
    public static let PAIRING_NOTENTITLED_RECOVERY = "your journal is paired, but it isn't on the paid plan — so it can't sync over the internet. on the same wi-fi as your journal, or over your own vpn, it connects directly without the plan."
    public static let PAIRING_DISCONNECT_CONFIRM = "disconnect this Mac from your journal? your journal keeps everything — you can pair again anytime."
    public static let JOURNAL_MARK_CONFIRM_QUESTION = "does this match your journal?"
    public static let JOURNAL_MARK_CONFIRM_SUBTEXT = "your journal shows this same mark in its network app. it should match — exactly."
    public static let JOURNAL_MARK_CONFIRM_BUTTON = "yes — this is my journal"
    public static let JOURNAL_MARK_MISMATCH_BUTTON = "that doesn't match"
    public static let JOURNAL_MARK_CONNECTING = "connecting…"
    public static let JOURNAL_MARK_MISMATCH_TITLE = "not connected"
    public static let JOURNAL_MARK_MISMATCH_BODY = "you said this mark doesn't match the one your journal shows — so we didn't connect this Mac. you may have pasted the wrong link, or something isn't right. try again, or reach us and we'll help."
    public static let JOURNAL_MARK_MISMATCH_FRESH_LINK = "get a fresh link"
    public static let JOURNAL_MARK_MISMATCH_SUPPORT = "email support@solstone.app"
    public static let SETTINGS_PREREQ_PERMISSIONS = "you'll also need to grant permissions →"
    public static let SETTINGS_NEXT_CONNECT_JOURNAL = "next: connect your journal →"
    public static let SETTINGS_NEXT_CHECK_STATUS = "next: check status →"
    public static let SETTINGS_TAB_DONE_A11Y = "configured"
    public static let SETTINGS_TAB_ATTENTION_A11Y = "needs attention"
    public static let SETTINGS_TAB_UPDATES_DONE_A11Y = "sol is up to date"
    public static let SETTINGS_ATTENTION_PERMISSIONS = "permissions needed"
    public static let SETTINGS_ATTENTION_JOURNAL = "journal setup needed"
    public static let SETTINGS_ATTENTION_UPDATE_AVAILABLE = "update available"
    public static let SETTINGS_ATTENTION_UPDATE_CHECK_FAILED = "update check failed"
    public static let MENUBAR_PERMISSIONS_OPEN_SETTINGS = "permissions needed — open settings →"
    public static let MENUBAR_OBSERVING_CONNECTED = "on, connected"
    public static let MENUBAR_OBSERVATION_WEDGE_OPEN_SETTINGS = "needs attention — open settings →"
    public static let MENUBAR_OBSERVING_OFFLINE_SAVED_LOCALLY = "on, offline (saved locally) →"
    public static let MENUBAR_LOCAL_ONLY_SETUP_JOURNAL = "on — set up your journal →"
    public static let MENUBAR_SYNC_PAUSED = "on, sync paused"
    public static let MENUBAR_STARTING = "starting…"
    public static let MENUBAR_A11Y_PERMISSIONS_NEEDED = "sol — permissions needed"
    public static let MENUBAR_A11Y_NEEDS_ATTENTION = "sol — needs attention"
    public static let MENUBAR_A11Y_ERROR = "sol — error"
    public static let MENUBAR_A11Y_STARTING = "sol — starting"
    public static let MENUBAR_A11Y_JOURNAL_SETUP_NEEDED = "sol — journal setup needed"
    public static let MENUBAR_A11Y_WAITING_FOR_JOURNAL = "sol — waiting for journal"
    public static let MENUBAR_A11Y_OBSERVING_SYNC_PAUSED = "sol — on, sync paused"
    public static let MENUBAR_A11Y_OBSERVING_SAVED_LOCALLY = "sol — on, saved locally"
    public static let MENUBAR_A11Y_PAUSED = "sol — paused"
    public static let MENUBAR_A11Y_OBSERVING_CONNECTED = "sol — on, connected"
    public static let SETTINGS_OBSERVATION_OBSERVING = "on"
    public static let SETTINGS_OBSERVATION_PAUSED = "paused"
    public static let SETTINGS_OBSERVATION_STARTING = "starting…"
    public static let SETTINGS_OBSERVATION_ERROR = "needs attention"
    public static let SETTINGS_HELP_ICON_FULL = "on — your data's reaching your journal"
    public static let SETTINGS_HELP_ICON_HALF = "on — saved on this Mac, not reaching your journal right now"
    public static let SETTINGS_HELP_ICON_PAUSED = "paused"
    public static let SETTINGS_HELP_ICON_ERROR = "needs your attention — permissions or a problem"
    public static let ERROR_LOGIN_ITEM = "couldn't update your login setting. try again, or toggle it off and on."
    public static let ERROR_SAVE_CONFIG = "couldn't save your settings. try again, or restart sol."
    public static let ERROR_START_OBSERVING = "couldn't turn sol on. check permissions in settings, then try again."

    public static func menubarErrorOpenSettings(_ message: String) -> String {
        "error: \(message) →"
    }

}
