public enum UICopy {
    public static let JOURNAL_MODE_THIS_MAC_LABEL = "this Mac"
    public static let JOURNAL_MODE_ANOTHER_MACHINE_LABEL = "another device"
    public static let JOURNAL_MODE_THIS_MAC_TRADEOFF = "solstone runs the full system on this Mac and your journal lives here. recommended if you're just getting started."
    public static let JOURNAL_MODE_ANOTHER_MACHINE_TRADEOFF = "this Mac becomes an observer that syncs to a journal that lives on another device — your other Mac, your home server, or a journal you've been invited to."
    public static let PAIRING_NOTENTITLED_RECOVERY = "your journal is paired, but it isn't on the paid plan — so it can't sync over the internet. on the same wi-fi as your journal, or over your own vpn, it connects directly without the plan."
    public static let PAIRING_DISCONNECT_CONFIRM = "disconnect this Mac from your journal? your journal keeps everything — you can pair again anytime."
    public static let SETTINGS_PREREQ_PERMISSIONS = "you'll also need to grant permissions →"
    public static let SETTINGS_NEXT_CONNECT_JOURNAL = "next: connect your journal →"
    public static let SETTINGS_NEXT_CHECK_STATUS = "next: check status →"
    public static let SETTINGS_TAB_DONE_A11Y = "configured"
    public static let SETTINGS_TAB_ATTENTION_A11Y = "needs attention"
    public static let SETTINGS_TAB_UPDATES_DONE_A11Y = "solstone is up to date"
    public static let SETTINGS_ATTENTION_PERMISSIONS = "permissions needed"
    public static let SETTINGS_ATTENTION_JOURNAL = "journal setup needed"
    public static let SETTINGS_ATTENTION_UPDATE_AVAILABLE = "update available"
    public static let SETTINGS_ATTENTION_UPDATE_CHECK_FAILED = "update check failed"
    public static let SETTINGS_RESTART_REQUIRED_BANNER = "restart needed for this to take effect — restart now →"
    public static let JOURNAL_SETUP_NEEDED_OPEN_SETTINGS = "journal setup needed — open settings"
    public static let JOURNAL_NEEDS_ATTENTION_OPEN_SETTINGS = "journal needs attention — open settings"
    public static let JOURNAL_RESTARTING = "journal restarting…"
    public static let RESTART_JOURNAL = "restart journal"
    public static let STOP_JOURNAL = "stop journal"
    public static let START_JOURNAL = "start journal"
    public static let JOURNAL_STATUS_RUNNING = "running"
    public static let JOURNAL_STATUS_RESTARTING = "restarting…"
    public static let JOURNAL_STATUS_SETUP_NEEDED = "setup needed"
    public static let DOCTOR_SETUP_NEEDED_TITLE = "can't find the journal runtime"
    public static let DOCTOR_SETUP_NEEDED_DETAIL = "the installed journal couldn't be located — try again, or reinstall from settings"
    public static let DOCTOR_CHECK_FAILED_TITLE = "the health check couldn't finish"
    public static let JOURNAL_STATUS_NEEDS_ATTENTION = "needs attention"
    public static let JOURNAL_STATUS_STOPPED = "stopped"
    public static let JOURNAL_WAITING_FOR_READINESS_MENU = "observing, waiting for journal"
    public static let JOURNAL_WAITING_FOR_READINESS_MENU_BUTTON = "observing, waiting for journal →"
    public static let JOURNAL_WAITING_FOR_READINESS = "waiting for journal to be ready"
    public static let MENUBAR_PERMISSIONS_OPEN_SETTINGS = "permissions needed — open settings →"
    public static let MENUBAR_OBSERVING_CONNECTED = "observing, connected"
    public static let MENUBAR_OBSERVATION_WEDGE_OPEN_SETTINGS = "observation isn't running — open settings →"
    public static let MENUBAR_OBSERVING_BUNDLED = "observing · your journal on this Mac"
    public static let MENUBAR_OBSERVING_OFFLINE_SAVED_LOCALLY = "observing, offline (saved locally) →"
    public static let MENUBAR_LOCAL_ONLY_SETUP_JOURNAL = "observing — set up your journal →"
    public static let MENUBAR_SYNC_PAUSED = "observing, sync paused"
    public static let MENUBAR_JOURNAL_STOPPED_BY_USER = "observing — your journal is stopped →"
    public static let MENUBAR_JOURNAL_WAITING = "waiting for journal…"
    public static let MENUBAR_STARTING = "starting…"
    public static let MENUBAR_A11Y_PERMISSIONS_NEEDED = "solstone observer — permissions needed"
    public static let MENUBAR_A11Y_NEEDS_ATTENTION = "solstone observer — needs attention"
    public static let MENUBAR_A11Y_ERROR = "solstone observer — error"
    public static let MENUBAR_A11Y_STARTING = "solstone observer — starting"
    public static let MENUBAR_A11Y_JOURNAL_SETUP_NEEDED = "solstone observer — journal setup needed"
    public static let MENUBAR_A11Y_JOURNAL_RESTARTING = "solstone observer — journal restarting"
    public static let MENUBAR_A11Y_JOURNAL_NEEDS_ATTENTION = "solstone observer — journal needs attention"
    public static let MENUBAR_A11Y_JOURNAL_NOT_RUNNING = "solstone observer — journal not running"
    public static let MENUBAR_A11Y_WAITING_FOR_JOURNAL = "solstone observer — waiting for journal"
    public static let MENUBAR_A11Y_OBSERVING_SYNC_PAUSED = "solstone observer — observing, sync paused"
    public static let MENUBAR_A11Y_OBSERVING_SAVED_LOCALLY = "solstone observer — observing, saved locally"
    public static let MENUBAR_A11Y_PAUSED = "solstone observer — paused"
    public static let MENUBAR_A11Y_OBSERVING_BUNDLED = "solstone observer — observing with your journal on this Mac"
    public static let MENUBAR_A11Y_OBSERVING_CONNECTED = "solstone observer — observing, connected"
    public static let SETTINGS_OBSERVATION_OBSERVING = "observing"
    public static let SETTINGS_OBSERVATION_PAUSED = "paused"
    public static let SETTINGS_OBSERVATION_STARTING = "starting…"
    public static let SETTINGS_OBSERVATION_ERROR = "needs attention"
    public static let SETTINGS_HELP_ICON_FULL = "observing — your data's reaching your journal"
    public static let SETTINGS_HELP_ICON_HALF = "observing — saved on this Mac, not reaching your journal right now"
    public static let SETTINGS_HELP_ICON_PAUSED = "paused"
    public static let SETTINGS_HELP_ICON_ERROR = "needs your attention — permissions or a problem"
    public static let JOURNAL_CHILD_BREAKER_TRIPPED = "journal stopped after repeated exits"
    public static let JOURNAL_MATERIALIZE_FAILED = "journal runtime couldn't be prepared"
    public static let JOURNAL_SPAWN_BLOCKED_PORTS = "journal ports are still in use"
    public static let JOURNAL_SPAWN_FAILED = "journal couldn't start"
    public static let JOURNAL_READINESS_TIMEOUT = "journal didn't become ready in time"
    public static let JOURNAL_SETUP_NEEDED_BEFORE_UPGRADE = "journal setup needed before upgrade can continue"
    public static let INSTALLER_INLINE_FAILURE_GENERIC = "setup hit a snag — retry below, or open details to share with support."
    public static let INSTALLER_READINESS_TIMEOUT = "solstone didn't become ready in time"
    public static let INSTALLER_READINESS_GATE_FAILED = "couldn't get solstone ready for this observer"
    public static let INSTALLER_VERIFY_INTEGRITY_LABEL = "verifying macOS security integrity"
    public static let ERROR_LOGIN_ITEM = "couldn't update your login setting. try again, or toggle it off and on."
    public static let ERROR_SAVE_CONFIG = "couldn't save your settings. try again, or restart solstone."
    public static let ERROR_START_OBSERVING = "couldn't start observing. check permissions in settings, then try again."

    public static func menubarErrorOpenSettings(_ message: String) -> String {
        "error: \(message) →"
    }

    public static func installerVerifyIntegrityWarning(library: String) -> String {
        "couldn't get \(library) ready; continuing"
    }
}
