import SolstoneCore

public enum UICopy {
    public static let SOURCES_TITLE = "sources"
    public static let SOURCES_HELP = "what you turn on here goes into your journal. both are on unless you turn one off."
    public static let SOURCES_MICROPHONE = "microphone"
    public static let SOURCES_SCREEN = "screen and system audio"
    public static let SOURCES_OFF = "off"
    public static let SOURCES_STARTING = "starting…"
    public static let SOURCES_OPEN_ACTION = "open sources →"
    public static let PERMISSIONS_OPEN_ACTION = "open permissions →"

    // Both switches off. The owner did that on purpose, so it is a calm state with a way back,
    // never a fault — but it is also the one state where nothing reaches the journal at all.
    public static let SOURCES_NONE = "both sources are off"
    public static let SOURCES_NONE_REASON = "nothing is going into your journal until you turn one back on."

    // Selected, but macOS hasn't granted either one.
    public static let SOURCES_UNAVAILABLE = "the source you turned on didn't start"
    public static let SOURCES_UNAVAILABLE_REASON = "the device may be in use by another app, or unplugged."
    public static let SOURCES_NONE_GRANTED = "what you turned on isn't granted yet"
    public static let SOURCES_GRANT_OR_CHANGE = "grant it below, or turn on the other source instead."

    // Per-source notices, shown beside a session that is running on the other source.
    public static let SOURCES_MIC_DENIED = "microphone permission not granted. screen and system audio can run on their own."
    public static let SOURCES_SCREEN_DENIED = "screen permission not granted. microphone can run on its own."
    public static let SOURCES_MIC_UNAVAILABLE = "microphone unavailable. screen and system audio are running."
    public static let SOURCES_SCREEN_UNAVAILABLE = "screen and system audio unavailable. microphone is running."

    public static let SOURCES_RESTART_READY = "granted. solstone needs to restart before what's on your screen can go into your journal."
    public static let SOURCES_RESTART = "restart now"

    public static func sourceNames(_ sources: CaptureSources) -> String {
        switch (sources.contains(.microphone), sources.contains(.screen)) {
        case (true, true): return "microphone, screen and system audio"
        case (true, false): return SOURCES_MICROPHONE
        case (false, true): return SOURCES_SCREEN
        case (false, false): return SOURCES_OFF
        }
    }

    public static func sourceStatus(_ sources: CaptureSources, isPaused: Bool = false) -> String {
        guard !sources.isEmpty else { return SOURCES_OFF }
        return "\(isPaused ? "paused" : "on") · \(sourceNames(sources))"
    }

    public static let JOURNAL_WINDOW_TITLE = "your journal"
    public static let JOURNAL_WINDOW_HELD = "your journal isn't connected yet"
    public static let JOURNAL_WINDOW_LOADING = "opening your journal…"
    public static let JOURNAL_WINDOW_ERROR = "your journal couldn't load"
    public static let JOURNAL_WINDOW_RETRY = "try again"
    public static let JOURNAL_MODE_THIS_MAC_LABEL = "this Mac"
    public static let JOURNAL_MODE_ANOTHER_MACHINE_LABEL = "another device"
    public static let PAIRING_LINK_PLACEHOLDER = "paste pairing link"
    public static let PAIRING_NOTENTITLED_RECOVERY = "your journal is paired, but it isn't on the paid plan, so it can't sync over the internet. on the same wi-fi as your journal, or over your own vpn, it connects directly without the plan."
    public static let PAIRING_DISCONNECT_CONFIRM = "disconnect this Mac from your journal? your journal keeps everything. you can pair again anytime."
    public static let JOURNAL_MARK_CONFIRM_QUESTION = "does this match your journal?"
    public static let JOURNAL_MARK_CONFIRM_SUBTEXT = "your journal shows this same mark in its network app. it should match, exactly."
    public static let JOURNAL_MARK_CONFIRM_BUTTON = "yes, this is my journal"
    public static let JOURNAL_MARK_MISMATCH_BUTTON = "that doesn't match"
    public static let JOURNAL_MARK_CONNECTING = "connecting…"
    public static let JOURNAL_MARK_MISMATCH_TITLE = "not connected"
    public static let JOURNAL_MARK_MISMATCH_BODY = "you said this mark doesn't match the one your journal shows, so we didn't connect this Mac. you may have pasted the wrong link, or something isn't right. try again, or reach us and we'll help."
    public static let JOURNAL_MARK_MISMATCH_FRESH_LINK = "get a fresh link"
    public static let JOURNAL_MARK_MISMATCH_SUPPORT = "email support@solstone.app"
    public static let SETTINGS_PREREQ_PERMISSIONS = "you'll also need to grant permissions →"
    public static let SETTINGS_NEXT_CONNECT_JOURNAL = "next: connect your journal →"
    public static let SETTINGS_NEXT_CHECK_STATUS = "next: check status →"
    public static let SETTINGS_LOCAL_JOURNAL_FOUND_EXISTING = "found an existing journal on this mac"
    public static let SETTINGS_LOCAL_JOURNAL_INSTALL_EXISTING = "install the journal app to bring it back online"
    public static let SETTINGS_LOCAL_JOURNAL_OPEN_EXISTING = "open the journal app to bring it back online"
    public static let SETTINGS_JOURNAL_OPEN = "open journal"
    public static let SETTINGS_TAB_DONE_A11Y = "configured"
    public static let SETTINGS_TAB_ATTENTION_A11Y = "needs attention"
    public static let SETTINGS_TAB_UPDATES_DONE_A11Y = "solstone is up to date"
    public static let SETTINGS_ATTENTION_PERMISSIONS = "permissions needed"
    public static let SETTINGS_ATTENTION_JOURNAL = "journal setup needed"
    public static let SETTINGS_ATTENTION_UPDATE_AVAILABLE = "update available"
    public static let SETTINGS_ATTENTION_UPDATE_CHECK_FAILED = "update check failed"
    public static let MENUBAR_SOURCES_OFF_OPEN_SETTINGS = "both sources are off · open sources →"
    public static let MENUBAR_NO_SOURCE_OPEN_SETTINGS = "waiting on a permission · open permissions →"
    public static let MENUBAR_OBSERVING_CONNECTED = "on, connected"
    public static let MENUBAR_OBSERVATION_WEDGE_OPEN_SETTINGS = "needs attention · open settings →"
    public static let MENUBAR_OBSERVING_OFFLINE_SAVED_LOCALLY = "on, offline (saved locally) →"
    public static let MENUBAR_LOCAL_ONLY_SETUP_JOURNAL = "on · set up your journal →"
    public static let MENUBAR_SYNC_PAUSED = "on, sync paused"
    public static let MENUBAR_STARTING = "starting…"
    public static let MENUBAR_A11Y_PERMISSIONS_NEEDED = "solstone · permissions needed"
    public static let MENUBAR_A11Y_NEEDS_ATTENTION = "solstone · needs attention"
    public static let MENUBAR_A11Y_ERROR = "solstone · error"
    public static let MENUBAR_A11Y_STARTING = "solstone · starting"
    public static let MENUBAR_A11Y_JOURNAL_SETUP_NEEDED = "solstone · journal setup needed"
    public static let MENUBAR_A11Y_WAITING_FOR_JOURNAL = "solstone · waiting for journal"
    public static let MENUBAR_A11Y_OBSERVING_SYNC_PAUSED = "solstone · on, sync paused"
    public static let MENUBAR_A11Y_OBSERVING_SAVED_LOCALLY = "solstone · on, saved locally"
    public static let MENUBAR_A11Y_PAUSED = "solstone · paused"
    public static let MENUBAR_A11Y_OBSERVING_CONNECTED = "solstone · on, connected"
    public static let SETTINGS_OBSERVATION_OBSERVING = "on · reaching your journal"
    public static let SETTINGS_OBSERVATION_CONNECTING = "connecting"
    public static let SETTINGS_OBSERVATION_PAUSED = "paused"
    public static let SETTINGS_OBSERVATION_NOT_REACHING = "on · not reaching your journal"
    public static let SETTINGS_OBSERVATION_NO_JOURNAL = "on · no journal"
    public static let SETTINGS_OBSERVATION_ATTENTION = "needs your attention"
    public static let SETTINGS_OBSERVATION_SAVED_LOCALLY = "on · saved on this mac, not reaching your journal right now"
    public static let SETTINGS_OBSERVATION_ERROR = "something's broken"
    public static let SETTINGS_TRY_AGAIN = "try again"
    public static let SETTINGS_TRY_AGAIN_IN_FLIGHT = "trying again…"
    public static let SETTINGS_OBSERVATION_RECOVERY_FALLBACK = "intake stopped and couldn't restart on its own."
    public static let SETTINGS_SETUP_GROUP_TITLE = "check my setup"
    public static let SETTINGS_SETUP_VERDICT_READY = "your setup is ready"
    public static let SETTINGS_SETUP_VERDICT_UNAVAILABLE = "some setup checks are unavailable"
    public static let SETTINGS_SETUP_SHARED_NOT_REQUIRED = "not needed on this Mac"
    public static let SETTINGS_SETUP_SHARED_COULD_NOT_CHECK = "couldn't check"
    public static let SETTINGS_SETUP_SHARED_GRANTED = "granted"
    public static let SETTINGS_SETUP_SHARED_NOT_GRANTED = "not granted"
    public static let SETTINGS_SETUP_SHARED_CHECKING = "checking"
    public static let SETTINGS_SETUP_SOL_APP_LABEL = "solstone app"
    public static let SETTINGS_SETUP_SOL_APP_READY = "in Applications"
    public static let SETTINGS_SETUP_SOL_APP_NEEDS_ATTENTION = "needs to be moved"
    public static let SETTINGS_SETUP_SOL_APP_ACTION = "open Applications →"
    public static let SETTINGS_SETUP_JOURNAL_APP_LABEL = "journal app"
    public static let SETTINGS_SETUP_JOURNAL_APP_READY = "installed"
    public static let SETTINGS_SETUP_JOURNAL_APP_NEEDS_ATTENTION = "not installed"
    public static let SETTINGS_SETUP_JOURNAL_APP_ACTION = "open journal settings →"
    public static let SETTINGS_SETUP_JOURNAL_LINK_LABEL = "your journal"
    public static let SETTINGS_SETUP_JOURNAL_LINK_READY = "linked"
    public static let SETTINGS_SETUP_JOURNAL_LINK_NEEDS_ATTENTION = "not linked"
    public static let SETTINGS_SETUP_JOURNAL_LINK_ACTION = "connect your journal →"
    public static let SETTINGS_SETUP_COMMAND_LINE_TOOLS_LABEL = "command line tools"
    public static let SETTINGS_SETUP_COMMAND_LINE_TOOLS_READY = "installed in ~/.local/bin"
    public static let SETTINGS_SETUP_COMMAND_LINE_TOOLS_NOT_INSTALLED = "not installed"
    public static let SETTINGS_SETUP_SCREEN_RECORDING_LABEL = "screen recording"
    public static let SETTINGS_SETUP_SCREEN_RECORDING_ACTION = "grant access →"
    public static let SETTINGS_SETUP_MICROPHONE_LABEL = "microphone"
    public static let SETTINGS_SETUP_MICROPHONE_ACTION = "grant access →"
    public static let SETTINGS_LAST_DELIVERY_LABEL = "last added to your journal"
    public static let SETTINGS_LAST_DELIVERY_NEVER = "nothing added yet"
    public static let SETTINGS_LAST_DELIVERY_NOT_LINKED = "your journal isn't linked"
    public static let SETTINGS_DIAGNOSTICS_TITLE = "diagnostics"
    public static let SETTINGS_DIAGNOSTICS_INTRO = "a short summary for troubleshooting."
    public static let SETTINGS_DIAGNOSTICS_SHOW = "show diagnostics"
    public static let SETTINGS_DIAGNOSTICS_HIDE = "hide diagnostics"
    public static let SETTINGS_DIAGNOSTICS_COPY = "copy diagnostics"
    public static let SETTINGS_DIAGNOSTICS_COPIED = "copied"
    public static let SETTINGS_DIAGNOSTICS_COPY_ANNOUNCEMENT = "diagnostics copied to the clipboard"
    public static let SETTINGS_DIAGNOSTICS_COPY_FAILED = "couldn't copy diagnostics"
    public static let SETTINGS_DIAGNOSTICS_APP_VERSION = "app version"
    public static let SETTINGS_DIAGNOSTICS_SCREEN_RECORDING = "screen recording"
    public static let SETTINGS_DIAGNOSTICS_MICROPHONE = "microphone"
    public static let SETTINGS_DIAGNOSTICS_SCREEN_AND_AUDIO = "sources"
    public static let SETTINGS_DIAGNOSTICS_LAST_JOURNAL_CONNECTION = "last journal connection"
    public static let SETTINGS_DIAGNOSTICS_INGEST_REASON = "journal intake"
    public static let SETTINGS_DIAGNOSTICS_INGEST_ROUTE = "journal intake address"
    public static let SETTINGS_DIAGNOSTICS_RECENT_STATE_CODES = "recent state codes"
    public static let SETTINGS_DIAGNOSTICS_GRANTED = "granted"
    public static let SETTINGS_DIAGNOSTICS_NOT_GRANTED = "not granted"
    public static let SETTINGS_DIAGNOSTICS_CHECKING = "checking"
    public static let SETTINGS_DIAGNOSTICS_COULD_NOT_CHECK = "couldn't check"
    public static let SETTINGS_DIAGNOSTICS_ON = "on"
    public static let SETTINGS_DIAGNOSTICS_PAUSED = "paused"
    public static let SETTINGS_DIAGNOSTICS_OFF = "off"
    public static let SETTINGS_DIAGNOSTICS_ERROR = "error"
    public static let SETTINGS_DIAGNOSTICS_NO_CONNECTION = "no connection yet"
    public static let SETTINGS_DIAGNOSTICS_NO_RECENT_CODES = "no recent state codes"
    public static let SETTINGS_PERMISSIONS_SCREEN_RECORDING_RESET_HINT = "if solstone is already in Applications but doesn't appear in Screen & System Audio Recording, remove any old solstone entry and try enabling screen recording again."
    public static let SETTINGS_NEXT_GRANT_PERMISSIONS = "next: grant permissions →"
    public static let SETTINGS_PERMISSIONS_SCREEN_EXPLAINER = "macOS lists this as Screen & System Audio Recording. grant it so what you share can go into your journal."
    public static let SETTINGS_PERMISSIONS_MIC_EXPLAINER = "macOS lists this as Microphone. grant it so what you share can go into your journal."
    public static let SETTINGS_PERMISSIONS_MIC_DENIED = "microphone access is off. allow solstone in Privacy & Security → Microphone."
    public static let SETTINGS_PERMISSIONS_MIC_RESTRICTED = "microphone access is restricted by this Mac."
    public static let SETTINGS_PERMISSIONS_OPEN_SYSTEM_SETTINGS = "open system settings →"
    public static let SETTINGS_HELP_ICON_RECORDING = "on · reaching your journal"
    public static let SETTINGS_HELP_ICON_CONNECTING = "connecting"
    public static let SETTINGS_HELP_ICON_PAUSED = "paused, or both sources off"
    public static let SETTINGS_HELP_ICON_ATTENTION = "needs your attention"
    public static let SETTINGS_HELP_ICON_OFFLINE = "on · saved on this mac, not reaching your journal right now"
    public static let SETTINGS_HELP_ICON_ERROR = "something's broken"
    public static let SETTINGS_LOG_EXPORT_TITLE = "recent logs"
    public static let SETTINGS_LOG_EXPORT_INTRO = "read up to the last 24 hours of logs from solstone on this mac. save a copy if you want one."
    public static let SETTINGS_LOG_EXPORT_ACTION = "show recent logs"
    public static let SETTINGS_LOG_EXPORT_WORKING = "reading recent logs…"
    public static let SETTINGS_LOG_EXPORT_SAVE = "save a copy…"
    public static let SETTINGS_LOG_EXPORT_FAILED = "couldn't read recent logs"
    public static let SETTINGS_LOG_EXPORT_PARTIAL = "some logs couldn't be read"
    public static let SETTINGS_LOG_EXPORT_EMPTY = "no logs in the last 24 hours"
    public static let SETTINGS_LOG_EXPORT_WRITE_FAILED = "couldn't save the copy"
    public static let SETTINGS_LOG_EXPORT_PREVIEW_SUBSET = "showing the newest %d of %d entries. saving writes all of them."
    // The status card names the same state the help legend names, in the same words,
    // so the red dot and its explanation cannot drift apart.
    public static let STATUS_CAPTURE_ERROR_TITLE = "something's broken"
    public static let ERROR_LOGIN_ITEM = "couldn't update your login setting. try again, or toggle it off and on."
    public static let ERROR_SAVE_CONFIG = "couldn't save your settings. try again, or restart solstone."
    public static let ERROR_START_OBSERVING = "couldn't turn intake on. check permissions in settings, then try again."

    public static func menubarErrorOpenSettings(_ message: String) -> String {
        "error: \(message) →"
    }

    public static func settingsSetupVerdictNeedsAttention(_ count: Int) -> String {
        count == 1 ? "1 thing needs attention" : "\(count) things need attention"
    }

}
